spring:
  datasource: # ?? DBaaS?? ????
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres # ?????? URL
    username: postgres.rvebwnoohxyvpearkbhp # ?????? ??? ??
    password: ripnyj-sefHan-kymri4 # ?????? ????
    driver-class-name: org.postgresql.Driver # PostgreSQL ???? ??? ??
