spring:
  application:
    name: boot-security
  # ?? ?? ??
  profiles:
    active: dev
    # ??? ? Docker? ???? prod? ????
  # ??? ? ?? (?? -> TIL?? ??)
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10 # ?? ??? ?
      minimum-idle: 5 # ?? ?? ??? ?
  # MyBatis ??
  mybatis:
    mapper-locations: classpath:mapper/*.xml # ?? XML ?? ?? ??
    type-aliases-package: org.example.bootsecurity.model.domain # ??? ?? ??? ??
    configuration:
      map-underscore-to-camel-case: true # ????? ???? ?? ??? ????? ?? ??
# ?? ??
logging:
  level:
    org.example.bootsecurity.model.mapper: DEBUG # mapper ???? ?? ??? DEBUG? ??